version: '3'
services:
  api:
    image: translator/backend
    build: ./backend    
    hostname: api
    depends_on:
      - postgres
      - redis
    env_file:
      - .env    
    ports:
      - "8000:8000"
    entrypoint: ["/app/wait-for-it.sh", "${PG_HOST}:${PG_PORT}", "--", "python", "-m", "translator.api"]
  worker:
    image: translator/backend
    build: ./backend
    hostname: worker
    depends_on:
      - postgres
      - redis
    env_file:
      - .env    
    entrypoint: ["/app/wait-for-it.sh", "${PG_HOST}:${PG_PORT}", "--", "python", "-m", "translator.worker"]
  migrator:
    image: translator/backend
    build: ./backend
    hostname: migrator
    depends_on:
      - postgres      
    env_file:
      - .env    
    entrypoint: ["/app/wait-for-it.sh", "${PG_HOST}:${PG_PORT}", "--", "fab", "db.init"]
  postgres:
    image: postgres:11-alpine
    hostname: postgres
    environment:
      - "PG_PASSWORD=postgres"
      - "PG_USER=postgres"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    hostname: redis
volumes:
  postgresql_data:
