// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Translator$ReactTemplate = require("./Translator.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Translator$ReactTemplate.make(/* array */[])), "translator");

/*  Not a pure module */
